version: '3'
services:

  postgres:
    # For more details on configuring the Postgres Docker image, see:
    #   https://hub.docker.com/_/postgres/
    build: src/database
    # Expose the default Postgres port on localhost
    ports:
      - '5432:5432'
    networks:
            football-viz-net:
                ipv4_address: 172.28.1.1
    container_name: postgres

    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'soccer'

    # Copy files from dbinit into the image so that they will be run on boot
    volumes:
      - soccer_database_volume:/var/lib/postgresql/data

  pgadmin:
    # For more details on configuring the pgadmin4 Docker image, see:
    #   https://hub.docker.com/r/dpage/pgadmin4/
    image: dpage/pgadmin4

    # Expose the web UI on localhost port 8080
    ports:
      - '8080:80'
    networks:
            football-viz-net:
                ipv4_address: 172.28.1.2
    container_name: pgadmin
    # Link this container to the postgres container with hostname 'postgres'
    external_links:
      - postgres:postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'

  python:
    image: my_python:latest
    networks:
            football-viz-net:
                ipv4_address: 172.28.1.3
    container_name: football-viz
    command: tail -F anything
    volumes:
      - ".:/data"

  passmap:
    build: visualisation/maps/passmap
    ports:
      - '8081:5000'
    networks:
            football-viz-net:
                ipv4_address: 172.28.1.4
    container_name: passmap
    volumes:
      - ".:/data"

volumes:
  soccer_database_volume:
    driver: local

networks:
    football-viz-net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
