---
title: "Loan players notebook"
author: "Benoit Pimpaud"
date: "23/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
library(knitr)
library(viridis)
```

## Import data

```{r,echo=FALSE,warning=FALSE}
data <- read.csv("../data/loan20172018.csv", dec=",")
data$Value = as.numeric(as.character(data$Value))
kable(sample_n(data,5))
```

## League analysis
```{r,echo=FALSE}
league <- data %>%
          group_by(League) %>%
          summarize(n=n(),avg_age=mean(Age),avg_value=mean(Value,na.rm=T)) %>%
          arrange(desc(n))
kable(league)

ggplot(league) + 
    geom_bar(aes(x = reorder(League,-n),y = n,fill = League),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_manual(values=c("#f06292","#ba68c8","#9575cd","#7986cb","#4db6ac"))+
    labs(x="", y="Players loaned",title="Number of players loaned by league",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

league <- data %>%
          group_by(League,Team) %>%
          summarize(n=n(),avg_age=mean(Age),av_loan=mean(n)) %>%
          group_by(League) %>%
          summarize(avg_loan = mean(av_loan)) %>%
          arrange(desc(avg_loan))

kable(league)

g1 <- ggplot(league) + 
    geom_bar(aes(x = reorder(League,-avg_loan),y = avg_loan,fill = League),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_manual(values=c("#f06292","#ba68c8","#9575cd","#7986cb","#4db6ac"))+
    labs(x="", y="Average players loaned by team",title="Average number of players loaned by league",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")
g1
ggsave(filename = paste0("average number of players loaned by league.png"),g1,width =14,height=8,dpi=300)

league <- data %>%
          group_by(League) %>%
          summarize(n=n(),avg_age=mean(Age),avg_value=mean(Value,na.rm=T)) %>%
          arrange(desc(n))
kable(league)

g2 <- ggplot(league) + 
    geom_bar(aes(x = reorder(League,-avg_age),y = avg_age,fill = League),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_manual(values=c("#f06292","#ba68c8","#9575cd","#7986cb","#4db6ac"))+
    labs(x="", y="Players loaned",title="Average age of players loaned by league",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

ggsave(filename = paste0("average age of players loaned by league.png"),g2,width =14,height=8,dpi=300)
```

## Big clubs analysis
```{r,echo=FALSE}
league <- data %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age),avg_value=mean(Value,na.rm=T)) %>%
          arrange(desc(n)) %>%
          slice(1:25)
  
kable(league)

ggplot(league) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill = n),stat = "identity",position = position_stack(reverse = FALSE)) +
  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by club - Top 25",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")
```

## Position analysis
```{r,echo=FALSE}
league <- data %>%
          group_by(Position) %>%
          summarize(n=n(),avg_age=mean(Age),avg_value=mean(Value,na.rm=T)) %>%
          arrange(desc(n))
kable(league)

g3 <- ggplot(league) + 
    geom_bar(aes(x = Position,y = n,fill = Position),stat = "identity",position = position_stack(reverse = FALSE)) +
    scale_x_discrete(limits=c("Keeper","Defender","Midfield","Forward"))+
    scale_fill_manual(values=c("#ba68c8","#9575cd","#7986cb","#4db6ac"))+
    labs(x="", y="Players loaned",title="Number of players loaned by position",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")
g3
ggsave(filename = paste0("number of players loaned by position.png"),g3,width =14,height=8,dpi=300)
```


### Premier League analysis
```{r,echo=FALSE}
pl<- data %>%
          filter(League=="Premier League") %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age)) %>%
          arrange(desc(n))
kable(pl)

g_pl <- ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill=n),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by their club in Premier League",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

g_pl
ggsave(filename = paste0("number of players loaned by their club in Premier League.png"),g_pl,width =14,height=8,dpi=300)

ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,avg_age),y = avg_age,fill=avg_age),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Age average",title="Average age from players loaned by their club in Premier League",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")
```

### LaLiga analysis
```{r,echo=FALSE}
pl<- data %>%
          filter(League=="LaLiga") %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age)) %>%
          arrange(desc(n))
kable(pl)

g_liga<-ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill=n),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by their club in La Liga",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

g_liga
ggsave(filename = paste0("number of players loaned by their club in La Liga.png"),g_liga,width =14,height=8,dpi=300)

ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,avg_age),y = avg_age,fill=avg_age),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Age average",title="Average age from players loaned by their club in La Liga",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

```

### Bundesliga analysis
```{r,echo=FALSE}
pl<- data %>%
          filter(League=="Bundesliga") %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age)) %>%
          arrange(desc(n))
kable(pl)

g_bundes<-ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill=n),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by their club in Bundesliga",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

g_bundes
ggsave(filename = paste0("number of players loaned by their club in Bundesliga.png"),g_bundes,width =14,height=8,dpi=300)

ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,avg_age),y = avg_age,fill=avg_age),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Age average",title="Average age from players loaned by their club in Bundesliga",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

```

### Serie A analysis
```{r,echo=FALSE}
pl<- data %>%
          filter(League=="Serie A") %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age)) %>%
          arrange(desc(n))
kable(pl)

g_serieA<-ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill=n),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by their club in Serie A",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

g_serieA
ggsave(filename = paste0("number of players loaned by their club in Serie A.png"),g_serieA,width =14,height=8,dpi=300)

ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,avg_age),y = avg_age,fill=avg_age),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Age average",title="Average age from players loaned by their club in Serie A",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

```

### Ligue 1 analysis
```{r,echo=FALSE}
pl<- data %>%
          filter(League=="Ligue1") %>%
          group_by(Team) %>%
          summarize(n=n(),avg_age=mean(Age)) %>%
          arrange(desc(n))
kable(pl)

g_ligue1 <- ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,n),y = n,fill=n),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Players loaned",title="Number of players loaned by their club in Ligue1",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

g_ligue1
ggsave(filename = paste0("number of players loaned by their club in Ligue 1.png"),g_ligue1,width =14,height=8,dpi=300)

ggplot(pl) + 
    geom_bar(aes(x = reorder(Team,avg_age),y = avg_age,fill=avg_age),stat = "identity",position = position_stack(reverse = TRUE)) +
    scale_fill_gradientn("Passes",colours = c("#a7ffeb","#64ffda","#1de9b6","#00bfa5"))+
 	  coord_flip()+
    labs(x="", y="Age average",title="Average age from players loaned by their club in Ligue1",subtitle="2017-2018 season",caption="Data from Transfermarkt\nby Benoit Pimpaud / @Ben8t",color="")+
 	theme_ipsum_rc()+
  theme(legend.position="none")

```

