WITH games AS (
	SELECT
		"startDate",
		game_id,
		home_team_id,
		away_team_id,
		home_score,
		away_score,
		result
	FROM metadata
)

SELECT
	games.*,
	team_style_cluster.cluster_0 AS "home_cluster_0",
    team_style_cluster.cluster_1 AS "home_cluster_1",
    team_style_cluster.cluster_2 AS "home_cluster_2",
    team_style_cluster.cluster_3 AS "home_cluster_3",
    team_style_cluster.cluster_4 AS "home_cluster_4",
    team_style_cluster.cluster_5 AS "home_cluster_5",
    team_style_cluster.cluster_6 AS "home_cluster_6",
    team_style_cluster.cluster_7 AS "home_cluster_7",
    team_style_cluster.cluster_8 AS "home_cluster_8",
    team_style_cluster.cluster_9 AS "home_cluster_9",
    team_style_cluster.cluster_10 AS "home_cluster_10",
    team_style_cluster.cluster_11 AS "home_cluster_11",
    team_style_cluster.cluster_12 AS "home_cluster_12",
    team_style_cluster.cluster_13 AS "home_cluster_13",
    team_style_cluster.cluster_14 AS "home_cluster_14",
    team_style_cluster.cluster_15 AS "home_cluster_15",
    team_style_cluster.cluster_16 AS "home_cluster_16",
    team_style_cluster.cluster_17 AS "home_cluster_17",
    team_style_cluster.cluster_18 AS "home_cluster_18",
    team_style_cluster.cluster_19 AS "home_cluster_19",
    team_style_cluster.cluster_20 AS "home_cluster_20",
    team_style_cluster.cluster_21 AS "home_cluster_21",
    team_style_cluster.cluster_22 AS "home_cluster_22",
    team_style_cluster.cluster_23 AS "home_cluster_23",
    team_style_cluster.cluster_24 AS "home_cluster_24",
    team_style_cluster.cluster_25 AS "home_cluster_25",
    team_style_cluster.cluster_26 AS "home_cluster_26",
    team_style_cluster.cluster_27 AS "home_cluster_27",
    team_style_cluster.cluster_28 AS "home_cluster_28",
    team_style_cluster.cluster_29 AS "home_cluster_29",
    team_style_cluster.cluster_30 AS "home_cluster_30",
    team_style_cluster.cluster_31 AS "home_cluster_31",
    team_style_cluster.cluster_32 AS "home_cluster_32",
    team_style_cluster.cluster_33 AS "home_cluster_33",
    team_style_cluster.cluster_34 AS "home_cluster_34",
    team_style_cluster.cluster_35 AS "home_cluster_35",
    team_style_cluster.cluster_36 AS "home_cluster_36",
    team_style_cluster.cluster_37 AS "home_cluster_37",
    team_style_cluster.cluster_38 AS "home_cluster_38",
    team_style_cluster.cluster_39 AS "home_cluster_39",
    team_style_cluster.cluster_40 AS "home_cluster_40",
    team_style_cluster.cluster_41 AS "home_cluster_41",
    team_style_cluster.cluster_42 AS "home_cluster_42",
    team_style_cluster.cluster_43 AS "home_cluster_43",
    team_style_cluster.cluster_44 AS "home_cluster_44",
    team_style_cluster.cluster_45 AS "home_cluster_45",
    team_style_cluster.cluster_46 AS "home_cluster_46",
    team_style_cluster.cluster_47 AS "home_cluster_47",
    team_style_cluster.cluster_48 AS "home_cluster_48",
    team_style_cluster.cluster_49 AS "home_cluster_49",
    away_team_style_cluster.cluster_0 AS "away_cluster_0",
    away_team_style_cluster.cluster_1 AS "away_cluster_1",
    away_team_style_cluster.cluster_2 AS "away_cluster_2",
    away_team_style_cluster.cluster_3 AS "away_cluster_3",
    away_team_style_cluster.cluster_4 AS "away_cluster_4",
    away_team_style_cluster.cluster_5 AS "away_cluster_5",
    away_team_style_cluster.cluster_6 AS "away_cluster_6",
    away_team_style_cluster.cluster_7 AS "away_cluster_7",
    away_team_style_cluster.cluster_8 AS "away_cluster_8",
    away_team_style_cluster.cluster_9 AS "away_cluster_9",
    away_team_style_cluster.cluster_10 AS "away_cluster_10",
    away_team_style_cluster.cluster_11 AS "away_cluster_11",
    away_team_style_cluster.cluster_12 AS "away_cluster_12",
    away_team_style_cluster.cluster_13 AS "away_cluster_13",
    away_team_style_cluster.cluster_14 AS "away_cluster_14",
    away_team_style_cluster.cluster_15 AS "away_cluster_15",
    away_team_style_cluster.cluster_16 AS "away_cluster_16",
    away_team_style_cluster.cluster_17 AS "away_cluster_17",
    away_team_style_cluster.cluster_18 AS "away_cluster_18",
    away_team_style_cluster.cluster_19 AS "away_cluster_19",
    away_team_style_cluster.cluster_20 AS "away_cluster_20",
    away_team_style_cluster.cluster_21 AS "away_cluster_21",
    away_team_style_cluster.cluster_22 AS "away_cluster_22",
    away_team_style_cluster.cluster_23 AS "away_cluster_23",
    away_team_style_cluster.cluster_24 AS "away_cluster_24",
    away_team_style_cluster.cluster_25 AS "away_cluster_25",
    away_team_style_cluster.cluster_26 AS "away_cluster_26",
    away_team_style_cluster.cluster_27 AS "away_cluster_27",
    away_team_style_cluster.cluster_28 AS "away_cluster_28",
    away_team_style_cluster.cluster_29 AS "away_cluster_29",
    away_team_style_cluster.cluster_30 AS "away_cluster_30",
    away_team_style_cluster.cluster_31 AS "away_cluster_31",
    away_team_style_cluster.cluster_32 AS "away_cluster_32",
    away_team_style_cluster.cluster_33 AS "away_cluster_33",
    away_team_style_cluster.cluster_34 AS "away_cluster_34",
    away_team_style_cluster.cluster_35 AS "away_cluster_35",
    away_team_style_cluster.cluster_36 AS "away_cluster_36",
    away_team_style_cluster.cluster_37 AS "away_cluster_37",
    away_team_style_cluster.cluster_38 AS "away_cluster_38",
    away_team_style_cluster.cluster_39 AS "away_cluster_39",
    away_team_style_cluster.cluster_40 AS "away_cluster_40",
    away_team_style_cluster.cluster_41 AS "away_cluster_41",
    away_team_style_cluster.cluster_42 AS "away_cluster_42",
    away_team_style_cluster.cluster_43 AS "away_cluster_43",
    away_team_style_cluster.cluster_44 AS "away_cluster_44",
    away_team_style_cluster.cluster_45 AS "away_cluster_45",
    away_team_style_cluster.cluster_46 AS "away_cluster_46",
    away_team_style_cluster.cluster_47 AS "away_cluster_47",
    away_team_style_cluster.cluster_48 AS "away_cluster_48",
    away_team_style_cluster.cluster_49 AS "away_cluster_49"
FROM games
LEFT JOIN team_style_cluster
ON games.home_team_id = team_style_cluster.team_id
LEFT JOIN (SELECT * FROM team_style_cluster) AS away_team_style_cluster
ON games.away_team_id = away_team_style_cluster.team_id