---
title: "Pass2Vec Experiments"
author: "Benoit Pimpaud"
date: "09/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.align="center") 
library(tidyverse)
library(hrbrthemes)
library(gghighlight)
library(knitr)
library(viridis)
set.seed(42)
```

## Data loading

```{r, echo=FALSE, warning=FALSE}
data <- read_csv("notebooks/pass2vec/data/test_seq5.csv", col_types=cols(team_id=col_character()))
kable(sample_n(data %>% select(id, t1, t2, sequence_length), 5))
```

## T-SNE plotting

```{r, echo=FALSE}
tsne_plot <- ggplot(data) + 
    geom_point(aes(x=t1, y=t2,color=sequence_length)) + 
    scale_color_viridis(option="viridis") + 
    theme_minimal() + 
    xlab("component 1") + 
    ylab("component 2")

tsne_plot

ggsave(filename="notebooks/pass2vec/img/tsne.png", tsne_plot, width=14, height=8, dpi=300)
```

## T-SNE with cluster on encoded features

```{r, echo=FALSE}
cluster_number <- 25
kmeans_result <- kmeans(data %>% 
                           select(contains("f_")) %>% 
                           na.omit(),
					    cluster_number, 
						iter.max = 50)
data_clustered <- data %>% 
	mutate(cluster=kmeans_result[["cluster"]]) %>% 
	select(id, team_id, t1, t2, cluster)

tsne_plot_cluster <- ggplot(data_clustered) + 
	geom_point(aes(x=t1, y=t2, color=factor(cluster))) + 
	scale_color_viridis_d() + 
	theme_minimal() + 
	xlab("component 1") + 
	ylab("component 2")

tsne_plot_cluster

ggsave(filename="notebooks/pass2vec/img/tsne_cluster.png", tsne_plot_cluster, width=14, height=8, dpi=300)
```

## Focusing on Manchester City

```{r, echo=FALSE}
manchester_city <- data_clustered %>% 
	group_by(team_id, cluster) %>% 
	summarise(count=n()) %>% 
	as.data.frame() %>% 
	filter(team_id==167) %>% 
	arrange(desc(count))

kable(sample_n(manchester_city, 5))

man_city_plot <- ggplot(data_clustered) + 
	geom_point(aes(x=t1, y=t2, color=factor(cluster))) + 
	scale_color_viridis_d() + 
    gghighlight(team_id==167) + 
	theme_minimal() + 
	xlab("component 1") + 
	ylab("component 2")

man_city_plot
```

## Teams dispatch

```{r, echo=FALSE}
spread_team_cluster <- data_clustered %>% 
	count(team_id, cluster) %>% 
	mutate(prop = prop.table(n)) %>%
	as.data.frame() %>%
    spread(key=cluster, value=prop)

kable(spread_team_cluster)

spread_team_cluster %>% gather(col, Value, -team_id) %>%
        mutate(row = factor(team_id, levels = rev(unique(team_id))), Value = Value) %>% 
        arrange(desc(Value)) %>%
        ggplot(aes(x=reorder(row, Value), y=col, fill = Value)) +
        geom_tile() +
        scale_fill_viridis(option="magma") + 
        theme_minimal() + 
        labs(x="", y="")
```